
* BASE DRINKS
  + Rush
  + Spin Left
  + Spin Right
  + Boom
  + Hop
  + Kick
* NOTE ON SPINS
  Spin Left and Spin Right work the same way, just in reverse. So I'll
  only be adding Spin Left to the below interactions. If both Spin
  Left and Spin Right are in a recipe, they cancel off. If they're the
  only two in the recipe, you get Water.
* OBJECTS
  + Energy Drink
    - Pick up by walking over, and you can drink or mix it later.
    - Other objects can overlap; cannot be picked up if there's a
      block or something blocking it.
    - Explosions destroy it.
  + Block
    - Can be pushed if there's only one in a row
    - Can be kicked
    - Not explosive by default but can be made so with certain recipes
    - Not affected by explosions
  + Cracked Block
    - Like a block, but destroyed on explosions
  + Bomb
    - Like a block but explosive by default
    - Explodes if another explosion hits it, causing a chain reaction
* RECIPES
  + ∅ :: Water; no effect
  + Kick :: Kick block or object in front, propelling it as far as possible.
  + Hop :: Hop over a one-block gap; cannot hop over blocks or other walls
  + Hop + Kick :: (Sequential) Hop, then Kick
  + Boom :: Explode in a 3x3 radius, destroying weak floors and blocks
  + Boom + Kick :: Kick block; block explodes when it hits a wall
  + Boom + Hop :: (Sequential) Hop, then Boom
  + Boom + Hop + Kick :: (Sequential) Hop, then [Boom + Kick]
  + Spin Left :: Spin in place; cosmetic effect
  + Spin Left + Kick :: Diagonal left kick
  + Spin Left + Hop :: Diagonal left hop
  + Spin Left + Hop + Kick :: (Sequential) Diagonal left hop + Diagonal left kick
  + Spin Left + Boom :: Boom w/ cosmetic animation
  + Spin Left + Boom + Kick :: Boom + Kick effect, but diagonally left
  + Spin Left + Boom + Hop :: (Sequential) [Spin Left + Hop], then [Spin Left + Boom]
  + Spin Left + Boom + Hop + Kick :: (Sequential) [Spin Left + Hop], then [Spin Left + Boom + Kick]
  + Rush :: Dash forward until stopped; can run over tightropes
  + Rush + Kick :: (Sequential) Rush, then Kick
  + Rush + Hop :: Hop forward until forced to stop
  + Rush + Hop + Kick :: [Hop + Kick] action until forced to stop
  + Rush + Boom :: (Sequential) Rush, then Boom
  + Rush + Boom + Kick :: (Sequential) Rush, then [Boom + Kick]
  + Rush + Boom + Hop :: [Hop + Boom] repeatedly until forced to stop
  + Rush + Boom + Hop + Kick :: [Hop + Boom + Kick] repeatedly until forced to stop
  + Rush + Spin Left :: Diagonal-left run until stopped
  + Rush + Spin Left + Kick :: Diagonal-left run until stopped, then kick diagonal left
  + Rush + Spin Left + Hop :: Diagonal-left hop until stopped
  + Rush + Spin Left + Hop + Kick :: Diagonal-left hop, then diagonal-left kick, until stopped
  + Rush + Spin Left + Boom :: (Sequential) [Rush + Spin Left], then Boom
  + Rush + Spin Left + Boom + Kick :: (Sequential) [Rush + Spin Left], then [Boom + Kick + Spin Left]
  + Rush + Spin Left + Boom + Hop :: Hop diagonal-left repeatedly until stopped, exploding each time
  + Rush + Spin Left + Boom + Hop + Kick :: Hop diagonal-left repeatedly until stopped, exploding and kicking each time
* STORY
  + Jerry from Tech Support has won a golden ticket in his favorite
    soda can: Bullseye Cola. He gets invited to the factory that
    manufactures the drink, where the CEO, Maximilian Sterling, gives
    him a virtual tour (Maximilian, himself, appears on various
    television screens in the facility). At the end, Maximilian
    reveals that he is a robotic reconstruction of the real
    Maximilian, who died twenty years ago. The robot has been looking
    for a replacement CEO and offers control over the factory to
    Jerry.
* CONTROLS
  + WASD or Arrow Keys :: Move
  + Shift + [WASD or Arrow Keys] :: Turn in place
