push_dia(new Dia(Mugshot.JERRY, WowThisPlaceIsEnormous, "Wow! This place is enormous!"));
push_dia(new Dia(Mugshot.MAX, HelloTherePrizeWinner, "Hello, there, prize winner! Welcome to the factory!"));
push_dia(new Dia(Mugshot.MAX, ImMaxSterling, "I'm Max Sterling, CEO and president of Bullseye Cola Incorporated."));
push_dia(new Dia(Mugshot.JERRY, GoodToMeetYouImJer, "Good to meet you, I'm Jer-"));
push_dia(new Dia(Mugshot.MAX, CongratulationsOnFindingAGoldenTicket, "Congratulations on finding the golden ticket in a can of our soda!"));
push_dia(new Dia(Mugshot.JERRY, YeahItWasAReallySoggy, "Yeah... it was a really soggy ticket by the time I found it..."));
push_dia(new Dia(Mugshot.MAX, AsYourPrizeYoureEntitled, "As your prize, you're entitled to a tour through our facility today!"));
push_dia(new Dia(Mugshot.MAX, ICantMakeItDownThere, "I can't make it down there in person, so I'll be guiding you over this intercom."));
push_dia(new Dia(Mugshot.MAX, IfYouCouldPleaseStep, "If you could, please step on the green star to begin your tour."));
push_dia(new Dia(Mugshot.EMPTY, undefined, "Use WASD or the arrow keys to move about the factory."));