push_dia(new Dia(Mugshot.JERRY, undefined, "Wow! This place is enormous!"));
push_dia(new Dia(Mugshot.MAX, undefined, "Hello, there, prize winner! Welcome to the factory!"));
push_dia(new Dia(Mugshot.MAX, undefined, "I'm Max Sterling, CEO and president of Bullseye Cola Incorporated."));
push_dia(new Dia(Mugshot.JERRY, undefined, "Good to meet you, I'm Jer-"));
push_dia(new Dia(Mugshot.MAX, undefined, "Congratulations on finding the golden ticket in a can of our soda!"));
push_dia(new Dia(Mugshot.JERRY, undefined, "Yeah... it was a really soggy ticket by the time I found it..."));
push_dia(new Dia(Mugshot.MAX, undefined, "As your prize, you're entitled to a tour through our facility today!"));
push_dia(new Dia(Mugshot.MAX, undefined, "I can't make it down there in person, so I'll be guiding you over this intercom."));
push_dia(new Dia(Mugshot.MAX, undefined, "If you could, please step on the green star to begin your tour."));
push_dia(new Dia(Mugshot.EMPTY, undefined, "Use WASD or the arrow keys to move about the factory."));